# Generated by Django 4.0.3 on 2022-04-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='product',
            name='gardning_category',
            field=models.CharField(choices=[('flower gardning', 'flower gardning'), ('vegetable gardning', 'vegetable plants'), ('herbal gardning', 'herbal gardning'), ('indoor gardning', 'indoor gardning')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='plant_category',
            field=models.CharField(choices=[('outdoor plant', 'outdoor plant'), ('indoor', 'indoor plant'), ('office plant', 'office plant')], default='', max_length=100),
        ),
    ]
