# Generated by Django 4.0.3 on 2022-04-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_transaction_product_gardning_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gardning_category',
            new_name='garden_category',
        ),
    ]
