# Generated by Django 4.0.3 on 2022-04-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_gardning_category_product_garden_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.TextField(default=''),
        ),
    ]
