# Generated by Django 4.0.3 on 2022-05-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='garden_category',
            field=models.CharField(choices=[('flower gardening', 'flower gardening'), ('vegetable gardening', 'vegetable plants'), ('herbal gardening', 'herbal gardening'), ('indoor gardening', 'indoor gardening')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('gardening', 'gardening'), ('plants', 'plants'), ('seed', 'seed'), ('fertilizer', 'fertilizer'), ('accessories', 'accessories')], max_length=100),
        ),
    ]
