# Generated by Django 4.0.3 on 2022-05-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_product_garden_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('state', models.CharField(default='gujarat', max_length=100)),
                ('street_address1', models.CharField(max_length=100)),
                ('street_address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
