# Generated by Django 4.0.3 on 2022-05-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_order_cart_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_maintainance',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_waterschedule',
            field=models.TextField(default=''),
        ),
    ]
