# Generated by Django 4.0.3 on 2022-05-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_gardening_category_product_garden_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='garden_category',
            field=models.CharField(choices=[('flower garden', 'flower garden'), ('vegetable garden', 'vegetable garden'), ('herbal garden', 'herbal garden'), ('indoor garden', 'indoor garden')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('garden', 'garden'), ('plants', 'plants'), ('seed', 'seed'), ('fertilizer', 'fertilizer'), ('accessories', 'accessories')], max_length=100),
        ),
    ]
