from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('cart/',views.cart,name='cart'),
    path('shop/',views.shop,name='shop'),
    path('contact/',views.contact,name='contact'),
    path('shop_details/',views.shop_details,name='shop_details'),
    path('category_garden/',views.category_garden,name='category_garden'),
    path('category_plant/',views.category_plant,name='category_plant'),
    path('category_seed/',views.category_seed,name='category_seed'),
    path('category_fertilizer/',views.category_fertilizer,name='category_fertilizer'),
    path('category_accessories/',views.category_accessories,name='category_accessories'),
    path('checkout/',views.checkout,name='checkout'),
    path('signup/',views.signup,name='signup'), 
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'), 
    path('change_password/',views.change_password,name='change_password'),
    path('forgot_password/',views.forgot_password,name='forgot_password'),
    path('new_password/',views.new_password,name='new_password'),
    path('otp/',views.verify_otp,name='verify_otp'),
    path('seller_index/',views.seller_index,name='seller_index'),
    path('seller_add_product/',views.seller_add_product,name='seller_add_product'),
    path('seller_view_product/',views.seller_view_product,name='seller_view_product'),
    path('seller_edit_product/<int:pk>/',views.seller_edit_product,name='seller_edit_product'),
    path('seller_delete_product/<int:pk>/',views.seller_delete_product,name='seller_delete_product'),
    path('product_detail/<int:pk>/',views.product_detail,name='product_detail'),
    path('add_to_wishlist/<int:pk>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('remove_from_wishlist/<int:pk>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('add_to_cart/<int:pk>/',views.add_to_cart,name='add_to_cart'),
    path('cart/',views.cart,name='cart'),
    path('remove_from_cart/<int:pk>/',views.remove_from_cart,name='remove_from_cart'),
    path('change_qty/',views.change_qty,name='change_qty'),
    path('pay/', views.initiate_payment, name='pay'),
    path('callback/', views.callback, name='callback'),
    path('myorders/', views.myorders, name='myorders'),
    path('billing_details/',views.billing_details,name='billing_details'),
    path('profile/',views.profile,name='profile'),
    path('profile_update/',views.profile_update,name='profile_update'),
    path('seller_profile/',views.seller_profile,name='seller_profile'),
    path('search/',views.search,name='search'),
]

